import json
import re

def fix_typos(text):
    if not text:
        return text
        
    replacements = {
        r"\bcúng cô\b": "củng cố",
        r"\bquyềt\b": "quyết",
        r"\bMiễn Nam\b": "Miền Nam",
        r"\bMiễn Bắc\b": "Miền Bắc",
        r"\bmiễn Nam\b": "miền Nam",
        r"\bmiễn Bắc\b": "miền Bắc",
        r"\bTỏng\b": "Tổng",
        r"\btiền công\b": "tiến công",
        r"\bchiền dịch\b": "chiến dịch",
        r"\bChiền dịch\b": "Chiến dịch",
        r"\bHỗ Chí Minh\b": "Hồ Chí Minh",
        r"\bmêẽ- thuột\b": "Mê Thuột",
        r"\bmê- thuột\b": "Mê Thuột",
        r"\bMê- Thuột\b": "Mê Thuột",
        r"\bthẳng lợi\b": "thắng lợi",
        r"\bkháng chiền\b": "kháng chiến",
        r"\bKháng chiền\b": "Kháng chiến",
        r"\bchồng Mỹ\b": "chống Mỹ",
        r"\bChồng Mỹ\b": "Chống Mỹ",
        r"\bghí vào\b": "ghi vào",
        r"\bchói lọi nhắt\b": "chói lọi nhất",
        r"\bsang ngời\b": "sáng ngời",
        r"\btoàn thẳng\b": "toàn thắng",
        r"\bcQa\b": "của",
        r"\bchQ\b": "chủ",
        r"\bĐáng Cộng sản\b": "Đảng Cộng sản",
        r"\bcủa Đáng\b": "của Đảng",
        r"\bchiền đầu\b": "chiến đấu",
        r"\bgian khỏ\b": "gian khổ",
        r"\bvả bảo vệ\b": "và bảo vệ",
        r"\bBao Ểìm\b": "Bao gồm",
        r"\bcá ba\b": "cả ba",
        r"\bChiên tranh\b": "Chiến tranh",
        r"\bchiên tranh\b": "chiến tranh",
        r"\bthẻ kéo dài\b": "thể kéo dài",
        r"\bthành phó\b": "thành phố",
        r"\bcó thẻ\b": "có thể",
        r"\bẤhông\b": "Không",
        r"\bdiểm\b": "điểm",
        r"\bThống nhắt\b": "Thống nhất",
        r"\bthống nhắt\b": "thống nhất",
        r"\bđắt nước\b": "đất nước",
        r"\bdưa ra\b": "đưa ra",
        r"\bTổ guốc\b": "Tổ quốc",
        r"\bthông nhất\b": "thống nhất",
        r"\bĐồng bảo\b": "Đồng bào",
        r"\bsuựm họp\b": "sum họp",
        r"\bngôi vào\b": "ngồi vào",
        r"\bbản đàm phán\b": "bàn đàm phán",
        r"\bnỏng cót\b": "nòng cốt",
        r"\bnỏng cốt\b": "nòng cốt",
        r"\bđặc hiệt\b": "đặc biệt",
        r"\bmỉnh\b": "mình",
        r"\bĐồng mỉnh\b": "Đồng minh",
        r"\bĐỏng Khởi\b": "Đồng Khởi",
        r"\bÁp Bắc\b": "Ấp Bắc",
        r"\bÍ\\p Bắc\b": "Ấp Bắc",
        r"\bPhQ\b": "Phủ",
        r"\btuyên bỏ\b": "tuyên bố",
        r"\bchắm dứt\b": "chấm dứt",
        r"\bđề quốc\b": "đế quốc",
        r"\bĐề quốc\b": "Đế quốc",
        r"\bchuyên sang\b": "chuyển sang",
        r"\bđánh dầu\b": "đánh dấu",
        r"\bchỉnh quyền\b": "chính quyền",
        r"\btiên hành\b": "tiến hành",
        r"\bkhủng hoáng\b": "khủng hoảng",
        r"\bxũ hội\b": "xã hội",
        r"\bchuân bị\b": "chuẩn bị",
        r"\bđảy mạnh\b": "đẩy mạnh",
        r"\bCổng hoà\b": "Cộng hoà",
        r"\blồi\b": "lối",
        r"\btiền lên\b": "tiến lên",
        r"\btính nước ta\b": "tỉnh nước ta",
        r"\btử Lai Châu\b": "từ Lai Châu",
        r"\bđiêm\b": "điểm",
        r"\btư bán\b": "tư bản",
        r"\bchú nghĩa\b": "chủ nghĩa",
        r"\bthời kỷ\b": "thời kỳ",
        r"\bÁfở rộng\b": "Mở rộng",
        r"\bđối ngọai\b": "đối ngoại",
        r"\bthúng\b": "tháng",
        r"\bkinh t thị trưởng\b": "kinh tế thị trường",
        r"\btổng quát của nước tạ\b": "tổng quát của nước ta",
        r"\bthời kệ\b": "thời kỳ",
        r"\bdẫn dắt\. chỉ phối\b": "dẫn dắt, chi phối",
        r"\bthể giới\b": "thế giới",
        r"\bthử mẩy\b": "thứ mấy",
        r"\btiên tiên\b": "tiên tiến",
        r"\bđậm đã\b": "đậm đà",
        r"\bsác dân tộc\b": "sắc dân tộc",
        r"\bĐăng nêu\b": "Đảng nêu",
        r"\btoán diện\b": "toàn diện",
        r"\bđảo tạo\b": "đào tạo",
        r"\bbình đăng\b": "bình đẳng",
        r"\bchề độ\b": "chế độ",
        r"\bsớ các nguyên tắc\b": "sở các nguyên tắc",
        r"\bcủng tôn trọng\b": "cùng tôn trọng",
        r"\bđỏi tên\b": "đổi tên",
        r"\bmáy lần\b": "mấy lần",
        r"\bcắp tư sản\b": "cấp tư sản",
        r"\bcắp công nhân\b": "cấp công nhân",
        r"\btiểu tư sản\b": "tiểu tư sản",
        r"\bcắp địa chủ\b": "cấp địa chủ",
        r"\bthầy phong trào\b": "thấy phong trào",
        r"\bhãi công\b": "bãi công",
        r"\btuyên bồ\b": "tuyên bố",
        r"\bđỏ\b": "đổ",
        r"\bchQ\b": "chủ",
        r"\bcQa\b": "của",
        r"\bcúmg cô\b": "củng cố",
        r"\bvả bảo\b": "và bảo",
        r"\bCông sản đáng\b": "Cộng sản đảng",
        r"\bCông sản\b": "Cộng sản",
        r"\btâmhợp\b": "tập hợp",
        r"\bBán án\b": "Bản án",
        r"\bcủng khỏ\b": "cùng khổ",
        r"\bTự chí trích\b": "Tự chỉ trích",
        r"\bChỉ bộ\b": "Chi bộ",
        r"\bQuảng châu\b": "Quảng Châu",
        r"\bHương cảng\b": "Hương Cảng",
        r"\bđuôi hồ\b": "đuổi hổ",
        r"\brú lòng thương\b": "rủ lòng thương",
        r"\byều tô\b": "yếu tố",
        r"\bViênNam\b": "Việt Nam",
        r"\bViêtiNam\b": "Việt Nam",
        r"\bViêuNam\b": "Việt Nam",
        r"\bViệ Nam\b": "Việt Nam",
        r"\bViệNam\b": "Việt Nam",
        r"\bViêtyNam\b": "Việt Nam",
        r"\btô chức\b": "tổ chức",
        r"\bđôn tiền phong\b": "đội tiên phong",
        r"\bĐôntiên\b": "Đội tiên",
        r"\bĐôntiền\b": "Đội tiên",
        r"\bĐô n tiên\b": "Đội tiên",
        r"\bDôntiền\b": "Đội tiên",
        r"\bDôntiên\b": "Đội tiên",
        r"\bÐôntiền\b": "Đội tiên",
        r"\bÐôntiên\b": "Đội tiên",
        r"\bvăn tắt\b": "vắn tắt",
        r"\bđiễn vào\b": "điền vào",
        r"\bchỗ trồng\b": "chỗ trống",
        r"\bban dlẳp hành\b": "ban chấp hành",
        r"\bTWS\b": "TW",
        r"\bTông BÍ thư\b": "Tổng Bí thư",
        r"\btằng lớp\b": "tầng lớp",
        r"\bdp vô sản\b": "cấp vô sản",
        r"\bchông để quốc\b": "chống đế quốc",
        r"\bbinh linh\b": "binh lính",
        r"\bHiệu rõ\b": "Hiểu rõ",
        r"\btính chắt\b": "tính chất",
        r"\bbản chắt\b": "bản chất",
        r"\bđầu tranh\b": "đấu tranh",
        r"\bÿ chỉ\b": "ý chí",
        r"\bcảm quyền\b": "cầm quyền",
        r"\bTỉnh chất\b": "Tính chất",
        r"\bđầu tiền\b": "đầu tiên",
        r"\bthô địa\b": "thổ địa",
        r"\bcốt lồi\b": "cốt lõi",
        r"\bnhắn mạnh\b": "nhấn mạnh",
        r"\bgiảnh\b": "giành",
        r"\bđúnh dầu\b": "đánh dấu",
        r"\bchuyên hướng\b": "chuyển hướng",
        r"\bchí đạo\b": "chỉ đạo",
        r"\bKhâu hiệu\b": "Khẩu hiệu",
        r"\bđót cháy\b": "đốt cháy",
        r"\bgiảnh chính quyền\b": "giành chính quyền",
        r"\bĐồng mỉnh\b": "Đồng minh",
        r"\bbùng nó\b": "bùng nổ",
        r"\bsụp đồ\b": "sụp đổ",
        r"\bđê quốc\b": "đế quốc",
        r"\btân dư\b": "tàn dư",
        r"\bmủ chữ\b": "mù chữ",
        r"\bgiặc dốt\b": "giặc dốt",
        r"\blãnh thô\b": "lãnh thổ",
        r"\bgiai cắp\b": "giai cấp",
        r"\bGiai cắp\b": "Giai cấp",
        r"\bnhắt\b": "nhất",
        r"\bNhắt\b": "Nhất",
        r"\bcách ménh\b": "cách mệnh",
        r"\bĐáng\b": "Đảng",
        r"\bĐăng\b": "Đảng",
        r"\bĐăng lao động\b": "Đảng lao động",
        r"\bĐăng Cộng sản\b": "Đảng Cộng sản",
        r"\bthông nhắt\b": "thống nhất",
    }
    
    for pattern, repl in replacements.items():
        text = re.sub(pattern, repl, text)
        
    text = text.replace("f\ Ùl\ll", "A.")
    text = text.replace("f.\\xc11-n;'z", "Cương")
    text = text.replace("sách lược vắn m.", "sách lược vắn tắt.")
    text = text.replace("sách lược vắn ml", "sách lược vắn tắt")
    text = text.replace("Điều lệ vắn ….", "Điều lệ vắn tắt")
    text = text.replace("Điều lẽ m'm m.", "Điều lệ vắn tắt.")
    text = text.replace("Điều lê nắn tắt", "Điều lệ vắn tắt")
    text = text.replace("Điều h:wủn tắt", "Điều lệ vắn tắt")
    text = text.replace("uuznợvuhh địp", "nhân dịp")
    text = text.replace("lìtnl", "Đảng")
    
    return text

def process():
    file_path = r'c:\vscode\code\TN_MMT\lichsudang\file1.json'
    with open(file_path, "r", encoding="utf-8") as f:
        data = json.load(f)
        
    for q in data["questions"]:
        q["question"] = fix_typos(q["question"])
        q["options"] = [fix_typos(opt) for opt in q["options"]]
        q["answer"] = fix_typos(q["answer"])
        
    with open(file_path, "w", encoding="utf-8") as f:
        json.dump(data, f, ensure_ascii=False, indent=2)
        
    print(f"Hoàn thành sửa lỗi chính tả.")

if __name__ == '__main__':
    process()
